Levels maintenance dn
OC-ComputerScience/performancescheduling-frontend pull request #18
Opened 2023-06-29 20:20 UTC by dbnorth

Add page for maintaining levels.

2023-06-30 22:48 UTC, AndrewClubb approved these changes
Everything worked well, just a couple style comments

2023-06-30 22:48 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +              {{ levelData.status === "Active" ? "Active" : "Disabled" }}
Do we need this logic? I think we can just use `{{levelData.status}}`

2023-06-30 22:48 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<script setup>
Do we want to disable levels? I didn't see any way to do this.

2023-06-30 22:48 UTC, AndrewClubb commented on src/components/admin/maintain/levels/MaintainLevels.vue
> +<script setup>
I provided screen shot in Agility, the spacing is a bit off before I added a level. It was then proper after that.

2023-06-30 22:48 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +          <v-textarea
I provided a screenshot in Agility, the blue outline was a bit strange inside the box.

2023-06-30 23:00 UTC, AndrewClubb requested changes

2023-06-30 23:00 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<style scoped>
Quick reminder these haven't been updated to remove the style

2023-07-01 19:22 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<script setup>
I could add it, but It doesn't seem like they will really every do it.  I don't think these every change much.

2023-07-01 19:24 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<style scoped>
done

2023-07-01 20:33 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +          <v-textarea
Well that was harder to find than it should have been
Fixed

2023-07-01 20:53 UTC, dbnorth commented on src/components/admin/maintain/levels/MaintainLevels.vue
> +<script setup>
I don't see what the spacing issue is?  I did look at the image.

2023-07-04 20:17 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<script setup>
If we are not planning to add it, do we still want to display "active" on the card and dialog body?

2023-07-04 20:17 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +              {{ levelData.status === "Active" ? "Active" : "Disabled" }}
In the current version of the branch this is still unfixed. Was this fixed but not committed?

2023-07-04 20:17 UTC, AndrewClubb commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +          <v-textarea
The blue box is gone, but I can click and drag the icon in the bottom right to resize the description box. While this could be useful for the admin, I can make it where the dialog box is taller than the screen and cannot access the buttons. Do we want to look into this or leave it for now?

2023-07-04 20:17 UTC, AndrewClubb commented on src/components/admin/maintain/levels/MaintainLevels.vue
> +<script setup>
Modifying the description lengths fixed this issue.

2023-07-05 00:28 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +              {{ levelData.status === "Active" ? "Active" : "Disabled" }}
fixed and then removed

2023-07-05 00:29 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +<script setup>
Removed Status from display

2023-07-05 02:16 UTC, AndrewClubb approved these changes
I am approving this PR in the case that we don't want to mess with the text box resizing. If you would like to merge, just resolve the last conversation then everything should work from there.

2023-07-05 04:07 UTC, dbnorth commented on src/components/admin/maintain/levels/LevelDialogBody.vue
> +          <v-textarea
I fixed so it can't grow

2023-07-05 04:07 UTC, merged