Add Major maintenance page
OC-ComputerScience/performancescheduling-frontend pull request #20
Opened 2023-06-29 23:52 UTC by dbnorth

Initial major maintenance page

2023-07-01 14:42 UTC, AndrewClubb requested changes
The page works pretty well but I have left a few comments.

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +              {{ majorData.status === "Active" ? "Active" : "Disabled" }}
This can be updated to be `{{ majorData.status }}`

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +          @click="props.isEdit ? updateMajor() : addMajor()"
When adding and editing a major, all the majors on the main page disappear. A screen refresh show the new/updated major.

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +<style scoped>
The <style scoped> can be removed

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MaintainMajorCard.vue
> +<style scoped>
The <style scoped> can be removed

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +function searchFilteredList() {
When entering "Eng" there should be plenty of majors that appear, but all majors disappear.

2023-07-01 14:42 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +<style scoped>
This <style scoped> can be removed

2023-07-01 14:42 UTC, AndrewClubb commented on src/services/MajorDataService.js
> +  disable(id) {
why create new functions rather than reusing the update(id) and set the status in the page? Do we plan to enable and disable majors from any other pages?

2023-07-01 17:39 UTC, dbnorth commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +<style scoped>
done

2023-07-01 17:43 UTC, dbnorth commented on src/services/MajorDataService.js
> +  disable(id) {
Because that is how the page I copied was coded. (Which is true for most of these changes.). I don't know of a need to disable and enable from other pages.  I will change it all of the maint, pages I have worked on.

2023-07-01 19:07 UTC, dbnorth commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +          @click="props.isEdit ? updateMajor() : addMajor()"
Fixed

2023-07-01 19:07 UTC, dbnorth commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +<style scoped>
fixed

2023-07-01 19:07 UTC, dbnorth commented on src/components/admin/maintain/majors/MaintainMajorCard.vue
> +<style scoped>
fixed

2023-07-01 19:07 UTC, dbnorth commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +function searchFilteredList() {
fixed

2023-07-01 19:07 UTC, dbnorth commented on src/services/MajorDataService.js
> +  disable(id) {
fixed

2023-07-01 21:14 UTC, dbnorth commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +function filterMajors() {
fixed

2023-07-01 21:14 UTC, dbnorth commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +              {{ majorData.status === "Active" ? "Active" : "Disabled" }}
fixed

2023-07-01 21:35 UTC, AndrewClubb requested changes
A lot better, but I noticed a bug in the cancel button

2023-07-01 21:35 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +              {{ majorData.status === "Active" ? "Active" : "Disabled" }}
In the current version I still see this as not fixed

2023-07-01 21:35 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +          Cancel
If changes are made (Name or isMusic) and the canceled, the changes were saved.

2023-07-02 19:26 UTC, dbnorth commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +              {{ majorData.status === "Active" ? "Active" : "Disabled" }}
one more time.

2023-07-02 19:27 UTC, dbnorth commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +          Cancel
fixed

2023-07-04 20:30 UTC, AndrewClubb requested changes

2023-07-04 20:30 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +}
If we modify the filter function to look like this, it allows us to only loop through the majors once. I know this won't make much difference performance wise, but I believe it is better to teach good practice if incoming students are needing to maintain this code.

```filteredMajors.value = filteredMajors.value.filter((major) => {
    return (
      (!statusFilterSelection.value ||
        major.status === statusFilterSelection.value) &&
      (!majorTypeFilterSelection.value ||
        major.isMusicMajor === majorTypeFilterSelection.value)
    );
  });

2023-07-04 20:30 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +              {{ editedMajorData.status === "Active" ? "Active" : "Disabled" }}
This can be modified to be `{{ editedMajorData.status }}`

2023-07-04 20:30 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MajorDialogBody.vue
> +          {{ props.majorData.status === "Disabled" ? "Enable" : "Disable" }}
This can be modified to be `{{ props.majorData.status }}`

2023-07-04 20:30 UTC, AndrewClubb commented on src/components/admin/maintain/users/MaintainUserCard.vue
> +async function disableUser(user) {
Do we not need to add `user.status = "Disabled"`?

2023-07-04 20:30 UTC, AndrewClubb commented on src/components/admin/maintain/users/MaintainUserCard.vue
> +async function enableUser(user) {
Do we not need to add `user.status = "Active"`?

2023-07-05 01:09 UTC, dbnorth commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +}
But if we spend all of our time revising code at this point we won't have a system to deliver.

I don't think the code you provided does anything since it does not include the actual filtering.

I changed it to this.
  filteredMajors.value = filteredMajors.value.filter(
    (major) =>
      (!statusFilterSelection.value ||
        major.status === statusFilterSelection.value) &&
      (!majorTypeFilterSelection.value ||
        major.isMusicMajor === majorTypeFilterSelection.value)
  );

2023-07-05 01:17 UTC, dbnorth commented on src/components/admin/maintain/users/MaintainUserCard.vue
> +async function disableUser(user) {
fixed

2023-07-05 01:17 UTC, dbnorth commented on src/components/admin/maintain/users/MaintainUserCard.vue
> +async function enableUser(user) {
fixed

2023-07-05 01:56 UTC, AndrewClubb commented on src/components/admin/maintain/majors/MaintainMajors.vue
> +}
I must have missed a few lines, but this was the end code I was meaning.

2023-07-05 02:02 UTC, AndrewClubb approved these changes

2023-07-05 02:04 UTC, merged