Add Maintain Event Types
OC-ComputerScience/performancescheduling-frontend pull request #21
Opened 2023-07-01 17:39 UTC by ethanimooney

Adds the Maintenance pages for EventTypes.

2023-07-01 17:43 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +              {{ eventTypeData.status === "Active" ? "Active" : "Disabled" }}
This can be modified to be `{{ eventTypeData.status }}`

2023-07-01 17:43 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/MaintainEventTypeCard.vue
> +            {{ eventTypeData.status === "Active" ? "Active" : "Disabled" }}
This can be modified to be `{{ eventTypeData.status }}`

2023-07-01 21:08 UTC, AndrewClubb requested changes

2023-07-01 21:08 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/MaintainEventTypes.vue
> +  if (instrumentTypeFilterSelection.value) {
Filtering by "Both" doesn't filter event types correctly. I wasn't able to edit/add event types to test Vocal or Instrumental

2023-07-01 21:08 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
The dialog box was too tall and the screen wasn't able to scroll. I could only see down to the "Private event" checkbox

![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/ff31585f-0185-477b-8d4a-9e2cd6aa04ca)

2023-07-02 02:10 UTC, ethanimooney commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
That's all of the data in the dialog

2023-07-02 02:11 UTC, ethanimooney commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
Oh minus the buttons I guess .. weird it usually forces scroll - will take a look

2023-07-03 18:51 UTC, ethanimooney commented on src/components/admin/maintain/eventTypes/MaintainEventTypes.vue
> +  if (instrumentTypeFilterSelection.value) {
Just had the wrong variable name in the filter - fixed.

2023-07-03 19:04 UTC, ethanimooney commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
Couldn't figure out how to fix this explicitly - it seems that the v-dialog component doesn't classify as overflow if it does, so I can't force the page to overflow. To at leas fix it somewhat I put the last two fields on the same line to make the dialog shorter.

2023-07-04 20:07 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/efa292b5-8b3a-43bf-8bd0-5d1edf7808c3)

2023-07-04 20:07 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
While that helped, I still cannot access the buttons at the bottom.

2023-07-06 18:15 UTC, ethanimooney commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +<script setup>
Fixed

2023-07-06 23:28 UTC, AndrewClubb requested changes
Looks great, just a simple fix left

2023-07-06 23:28 UTC, AndrewClubb commented on src/components/admin/maintain/eventTypes/EventTypeDialogBody.vue
> +const editedEventTypeData = ref(props.eventTypeData);
Need to change this to `const editedEventTypeData = ref(Object.assign({}, props.eventTypeData));`

2023-07-07 01:02 UTC, AndrewClubb approved these changes

2023-07-07 01:02 UTC, merged