Composer maiintenance dn
OC-ComputerScience/performancescheduling-frontend pull request #24
Opened 2023-07-03 18:31 UTC by dbnorth

2023-07-04 20:54 UTC, AndrewClubb requested changes

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +      delete editedComposerData.value["createdAt"];
Why do we need to delete the `createdAt` tag? Won't the values be the same and thus have no effect on the data?

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +                editedComposerData.status === "Active" ? "Active" : "Disabled"
This can be changed to `{{ editedComposerData.status }}`

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +              similarComposerCheck(editedComposerData),
Are we sure we want to prevent the admin from creating a new composer if there is a similar one? I would think we would rather warn them and force them to approve the creation.

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/MaintainComposers.vue
> +const statusFilterOptions = ["Active", "Disabled", "Pending"];
Are we sure we want to hard code these? This isn't flexible in the case more status options are added to the system. It also made me think there were disabled and pending composers because the options were there.

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/MaintainComposers.vue
> +const perPage = 15;
With 15, I cannot see the filter features at the top and the pagination at the bottom. Do we want to consider lowering this value so both features are available without scrolling?

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +            {{ composerData.lastName }}, {{ composerData.firstName }}
Do we want to make this a little smarter so the comma is conditional if there is a last name? It looks strange to me looking like this for "Henry VIII" and "Anonymous"

![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/f23f4609-daab-456f-ba2c-af7c634257b8)

2023-07-04 20:54 UTC, AndrewClubb commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +<template>
The dialog box is long enough where I cannot see the buttons at the bottom.

![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/af624c85-2280-445b-a473-f51781a652c1)

2023-07-05 01:27 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +                editedComposerData.status === "Active" ? "Active" : "Disabled"
fixed

2023-07-05 01:35 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposers.vue
> +const statusFilterOptions = ["Active", "Disabled", "Pending"];
There can be Disabled and Pending composers.   There would be Disabled composers if they don't want to use that composer (mostly would mean you can't add a new piece for that composer any more, maybe it is a duplicate). If a student adds a composer it will be added as Pending for admin to change to Active.  I have not yet added all the logic we might want if they don't  want to change from Pending to Active.

2023-07-05 01:37 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +              similarComposerCheck(editedComposerData),
Clearly I though it would be ok.  I has to be pretty similar.  These are not exact match but pretty close.  I think we can leave it and change how close or different we want it to be.

2023-07-05 01:44 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +      delete editedComposerData.value["createdAt"];
I don't know, Ethan had it in the code I copied.  I thought about it and though there might be a reason I didn't think of.

I don't know why the createdAt needs to be delete because it will not change.  I don't know if the updated has to be delete to get and update value.  I thought Sequelize manages this.

2023-07-05 02:14 UTC, AndrewClubb commented on src/components/admin/maintain/composers/MaintainComposers.vue
> +const statusFilterOptions = ["Active", "Disabled", "Pending"];
I was more questioning if we wanted to create this list dynamically based upon all the composers from the getAll(). It would allow the filter to only show status variables that exist in the list of composers.

2023-07-05 03:28 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +            {{ composerData.lastName }}, {{ composerData.firstName }}
Fixed it.  Change the spacing a little so it will all fit.

2023-07-05 03:43 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +<template>
at 100% I can see the top and bottom, but I did make it shorter by putting birth and death on the same row.

2023-07-05 03:44 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposers.vue
> +const perPage = 15;
Fixed it. Change the spacing a little so it will all fit.

2023-07-05 03:58 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +            {{ composerData.lastName }}, {{ composerData.firstName }}
Fix not to show comma if either name is null

2023-07-06 18:08 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +      delete editedComposerData.value["createdAt"];
removed

2023-07-06 18:09 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +<template>
did you look at it after I removed a row?

2023-07-07 00:23 UTC, AndrewClubb commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +            :rules="[
The database allows for nullable first name and last name. Do we want to require these fields on the UI?

2023-07-07 05:08 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +            :rules="[
Well one of them should not be null

2023-07-07 05:09 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +            :rules="[
I will work on it

2023-07-07 13:56 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +  return composer.lastName != null || composer.firstName != null
fixed

2023-07-07 14:03 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +  props.composerData.lastName.length == 0
fixed

2023-07-07 21:02 UTC, AndrewClubb requested changes

2023-07-07 21:02 UTC, AndrewClubb commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +  props.composerData.lastName.length == null ||
Is this meant to be `props.composerData.lastName == null` and drop the `.length`?

2023-07-07 22:24 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposerCard.vue
> +  props.composerData.lastName.length == null ||
fixed it

2023-07-08 01:47 UTC, AndrewClubb approved these changes

2023-07-08 01:47 UTC, merged