Add Validation to Maintain Users Page
OC-ComputerScience/performancescheduling-frontend pull request #25
Opened 2023-07-03 19:40 UTC by ethanimooney

Adds validation to the user dialog and user instrument dialog

2023-07-04 21:13 UTC, AndrewClubb requested changes

2023-07-04 21:13 UTC, AndrewClubb commented on src/components/admin/maintain/users/UserDialogBody.vue
> +      delete editedUserData.value["createdAt"];
Do we want to delete the `createdAt` tag since they should be the same value in the db?

2023-07-04 21:13 UTC, AndrewClubb commented on src/components/admin/maintain/users/UserDialogBody.vue
> +              {{ userData.status === "Active" ? "Active" : "Disabled" }}
This can be modified to be `{{ userData.status }}`

2023-07-04 21:13 UTC, AndrewClubb commented on src/components/admin/maintain/users/UserInstrumentDialogBody.vue
> +              }}
This can be modified to be `{{ studentInstrumentData.status }}`

2023-07-04 21:13 UTC, AndrewClubb commented on src/components/admin/maintain/users/UserInstrumentDialogBody.vue
>  <template>
With the addition of the phone number, I can no longer access the buttons.
![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/9b4b9ce3-7e09-4844-8152-eeb4a490e71c)

2023-07-06 18:05 UTC, ethanimooney commented on src/components/admin/maintain/users/UserDialogBody.vue
> +      delete editedUserData.value["createdAt"];
Realized this isn't actually needed - removed.

2023-07-06 18:06 UTC, ethanimooney commented on src/components/admin/maintain/users/UserInstrumentDialogBody.vue
>  <template>
Phone number didn't get added anytime recently, this has just been an issue forever apparently. Looking at it now.

2023-07-06 18:12 UTC, ethanimooney commented on src/components/admin/maintain/users/UserInstrumentDialogBody.vue
>  <template>
Moving the v-form inside the v-card tag fixed it.

2023-07-06 23:40 UTC, AndrewClubb approved these changes

2023-07-06 23:40 UTC, merged