added pieces maintenance
OC-ComputerScience/performancescheduling-frontend pull request #27
Opened 2023-07-04 18:54 UTC by dbnorth

2023-07-04 21:04 UTC, AndrewClubb requested changes

2023-07-04 21:04 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +              {{ editedPieceData.status === "Active" ? "Active" : "Disabled" }}
This can be modified to be `{{ editedPieceData.status }}`

2023-07-04 21:04 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +            {{ pieceData.composer.lastName }},
When launching the page, none of the pieces appeared. And I received this error in the console.

![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/e119dea0-8f70-497b-8891-6eb1040f0c06)

2023-07-05 04:10 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +              {{ editedPieceData.status === "Active" ? "Active" : "Disabled" }}
fixed

2023-07-05 04:16 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +            {{ pieceData.composer.lastName }},
You need to also check out the backend branch that goes with this story.
v: pieces-maintenance-dn, 
n:pieces-maintenance-dn

2023-07-06 02:41 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +      delete editedPieceData.value["createdAt"];
removed

2023-07-07 00:46 UTC, AndrewClubb requested changes

2023-07-07 00:46 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +      compareTwoStrings(c.title.toLowerCase(), piece.title.toLowerCase()) >=
I don't think we should limit based upon similarity alone. It is very possible that two composers write two songs with the same (or similar) titles. So I think this should be updated to also check that the composers aren't the same.

2023-07-07 05:06 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +      compareTwoStrings(c.title.toLowerCase(), piece.title.toLowerCase()) >=
fixed

2023-07-07 12:46 UTC, AndrewClubb approved these changes

2023-07-07 12:47 UTC, merged