Instrument maintenance dn
OC-ComputerScience/performancescheduling-frontend pull request #29
Opened 2023-07-07 13:28 UTC by dbnorth

2023-07-07 21:23 UTC, AndrewClubb requested changes

2023-07-07 21:23 UTC, AndrewClubb commented on src/components/admin/maintain/instruments/InstrumentDialogBody.vue
> +      delete editedInstrumentData.value["updatedAt"];
These can be removed

2023-07-07 22:07 UTC, dbnorth commented on src/components/admin/maintain/instruments/InstrumentDialogBody.vue
> +      delete editedInstrumentData.value["updatedAt"];
removed

2023-07-08 02:03 UTC, AndrewClubb approved these changes

2023-07-08 02:04 UTC, merged