Student rep maint dn
OC-ComputerScience/performancescheduling-frontend pull request #35
Opened 2023-07-17 23:17 UTC by dbnorth

Able to add an edit student pieces, can't yet add composer and pieces that are not in the standard list yet, but want to get this much done for now.

2023-07-27 00:56 UTC, AndrewClubb requested changes
I suggest removing the file "old-StudentRepertoire.vue"

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
Both translation fields are not saved for the admin to verify

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +  console.log("last=" + editedStudentPieceData.value.piece.composer.lastName);
This console.log should be removed

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +      await StudentPieceDataService.create(editedStudentPieceData.value)
Before we create/update, we should check if the piece already exists for that piece/instrument/semester

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +            v-model="editedStudentPieceData.piece.composer.lastName"
I think displaying the full name is a better as two composers can have the same last name

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +    );
I think it would be nice if the search also found by composer names

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +function filterStudentPieces() {
Setting any of the filters clears out the entire list

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/MaintainStudentPieceCard.vue
> +            {{ studentpieceData.piece.composer.lastName }},
I think this should be updated because composers don't always have a first name and last name. So the comma would just be free floating

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +  await ComposerDataService.getAll("lastName", false)
I think it makes more sense for composers to be list alphabetically rather than reverse-alphabetical

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +  await PieceDataService.getAll("title", false)
I think it makes more sense for pieces to be list alphabetically rather than reverse-alphabetical

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +              <v-list-item
I am pretty sure this can be reduced to:
<v-list-item @click="onClick">
{{ item.raw.firstName != null && item.raw.firstName.length != 0 ? item.raw.lastName : "" + item.raw.firstName != null && item.raw.firstName.length != 0 && item.raw.lastName != null && item.raw.lastName.length != 0 ? ", " : "" + item.raw.lastName != null && item.raw.lastName.length != 0 ? item.raw.firstName : "" }}
</v-list-item>

and this removes the need for multiple list items

2023-07-27 00:56 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +    <StudentPieceDialogBody
I think it makes sense for these to be ordered by semesters newer to later (it currently orders later to newer)

2023-07-27 00:56 UTC, AndrewClubb commented on src/views/BaseView.vue
> +
To keep everything grouped, I would remove this space

2023-07-28 03:23 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
I was not able to reproduce this.

I was able to find a problem that if the student clicked the edit piece button and change translations field click save and then click edit again the new values were not displayed (they did get saved)

2023-07-28 03:24 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +  console.log("last=" + editedStudentPieceData.value.piece.composer.lastName);
done

2023-07-28 03:52 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +            v-model="editedStudentPieceData.piece.composer.lastName"
I do to, but I cant figure out how to make it work that way

2023-07-28 04:28 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +    );
done

2023-07-28 04:30 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +  await ComposerDataService.getAll("lastName", false)
done

2023-07-28 04:49 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +    <StudentPieceDialogBody
ok

2023-07-28 04:51 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +              <v-list-item
ok

2023-07-28 04:53 UTC, dbnorth commented on src/views/BaseView.vue
> +
ok

2023-07-28 05:28 UTC, dbnorth commented on src/components/student/repertoire/MaintainStudentPieceCard.vue
> +            {{ studentpieceData.piece.composer.lastName }},
I fixed it, but I can' make it select the composers with just first names to test it

2023-07-28 05:28 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +              <v-list-item
I tried this code but it didn't work.  You are welcome to try.

2023-07-28 13:33 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +      await StudentPieceDataService.create(editedStudentPieceData.value)
done

2023-07-30 03:04 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +            v-model="editedStudentPieceData.piece.composer.lastName"
Fixed

2023-07-30 03:22 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +              <v-list-item
Got this to work
              <v-list-item @click="onClick">
                {{
                  item.raw.firstName +
                  (item.raw.firstName != null &&
                  item.raw.firstName.length != 0 &&
                  item.raw.lastName != null &&
                  item.raw.lastName.length != 0
                    ? ", "
                    : "") +
                  item.raw.lastName
                }}
              </v-list-item>

2023-07-31 14:41 UTC, dbnorth commented on src/components/student/repertoire/MaintainStudentPieceCard.vue
> +            {{ studentpieceData.piece.composer.lastName }},
Tested

2023-08-07 02:27 UTC, AndrewClubb reviewed
This is looking better, just a couple more comments. Also, I have feedback on the backend PR.

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +              v-if="statusFilterSelection != null"
this needs to be updated to include the semester filter

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +        v-if="statusFilterSelection != null"
this needs to be updated to include semester filter

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +        </v-btn>
When editing a piece in my rep, I didn't change any data and clicked save. I got `This is piece, instrument and semester already exist for this student pieces` I think this error shouldn't appear since the piece it is finding is the piece I am editing

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/student/repertoire/StudentRepertoire.vue
> +const statusFilterOptions = ["Active", "Disabled", "Pending"];
Is there ever a case when a repertoire piece will be pending? If not this should be removed

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
>  const props = defineProps({
When a piece is pending, there is only the option to disable the piece. If pending I would expect activate to also be an option

2023-08-07 02:27 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
>    <v-dialog v-model="createOrEditDialog" persistent max-width="600px">
Since this is the repertoire add dialog, will you add it to the student signup dialog?

2023-08-14 01:16 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +              v-if="statusFilterSelection != null"
fixed

2023-08-14 02:34 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +        v-if="statusFilterSelection != null"
done

2023-08-14 02:40 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
>    <v-dialog v-model="createOrEditDialog" persistent max-width="600px">
Are you asking if we should have a way for student to add their repertoire when they sign up for events? (StudentEventSignupDialog).  If so, we should add another story for it.

2023-08-14 02:41 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +const statusFilterOptions = ["Active", "Disabled", "Pending"];
done

2023-08-14 02:43 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
>  const props = defineProps({
When a piece is pending only an Admin and change it to Active.

None of the screens in the  student repertoire  allow the student to change the status at all.

2023-08-14 02:45 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
>    <v-dialog v-model="createOrEditDialog" persistent max-width="600px">
The button is already on the signup dialog box. Is it that much more work to hook up your new repertoire dialog to that button? If so, that can be another story but I don't see why it needs to be split up as that would be an expected feature from the student's perspective

2023-08-14 02:46 UTC, AndrewClubb commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
>  const props = defineProps({
Correct, but as an Admin when the piece is pending the admin can only disable the piece. There is no way for them to accept the student's changes unless they disable and reenable the piece.

2023-08-16 00:49 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
>    <v-dialog v-model="createOrEditDialog" persistent max-width="600px">
I have added add student piece it to the event sign up  - can only add pieces for the event semester and instrument selected.  It should show in the list immediately.

I have commented out the event piece selection search.  I think the list for the semester and instrument is short (all that show in the list) and the search resets the selection if you use it.

You will need to test the Admin piece add and edit, the event signup add piece and the Repertoire edit piece since they were all impacted by this change.

2023-08-16 02:39 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
> +<script setup>
Can now add pieces and composers

2023-08-16 02:41 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
> +        <v-btn
Can now enable if a composer is Pending

2023-08-28 04:06 UTC, JuliaFlores21 reviewed
I cannot test a lot of things from the StudentRepertoire page because it throws me two warnings and one error message. I put the screenshot in the beginning of the StudentRepertoire page. Do I need to add any data before I need to test this? I already am a student and have instruments.

2023-08-28 04:06 UTC, JuliaFlores21 commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +          Add Composer
There is the following warning message when I click the "Add Composer" button:

![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/111401638/d61ce99c-43a7-4bf2-8b9e-4ded2cf52f95)

2023-08-28 16:23 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +          <v-select
Fixed

2023-08-28 16:24 UTC, dbnorth commented on src/components/student/repertoire/StudentRepertoire.vue
it works ok for me.  did you npm install?

2023-08-28 16:28 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
Not sure how tight to make it.  Especially when the last name matches but the first name does not.

2023-08-28 16:32 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposers.vue
Did you find any that were BC i didn't

2023-08-28 17:44 UTC, dbnorth commented on src/components/student/repertoire/StudentPieceDialogBody.vue
> +          Add Composer
Fixed

2023-08-28 17:46 UTC, dbnorth commented on src/components/admin/maintain/composers/MaintainComposers.vue
fixed

2023-08-28 18:03 UTC, dbnorth commented on src/components/admin/maintain/composers/ComposerDialogBody.vue
made it easier to match

2023-08-31 22:13 UTC, JuliaFlores21 approved these changes
okay

2023-08-31 22:14 UTC, JuliaFlores21 approved these changes
looks good

2023-08-31 22:15 UTC, merged