Student view performances
OC-ComputerScience/performancescheduling-frontend pull request #37
Opened 2023-07-28 02:48 UTC by dbnorth

Need to use the student-view-perf-dn backend to test

2023-08-07 02:58 UTC, AndrewClubb requested changes

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformances.vue
> +    console.log(response.data);
This should be removed

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformances.vue
> +  console.log(performances.value);
this should be removed

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformanceCard.vue
> +<script setup>
I would like to see if the student pass or failed each signup

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformanceCard.vue
> +                    View Critique
I think this button should only appear if there are actually critiques attached to the piece

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/PerformanceDialogBody.vue
> +          >{{ critique.userRole.user.firstName }}
there is  an additional `>` that should be removed

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/PerformanceDialogBody.vue
> +                  >Accuracy - Grade: {{ critique.accuracyGrade }}
in the database, overallComment is the only guaranteed attribute. Since that's the case I would add a v-if to these components.

2023-08-07 02:58 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformanceCard.vue
> +<script setup>
Please add padding to the bottom of the card so the border is the same all the way around. Also, notice the `view critique` text size is larger than the background.
![image](https://github.com/OC-ComputerScience/performancescheduling-frontend/assets/96355729/f0fab8db-0d39-4f4a-a0c6-69202f410b1f)

2023-08-09 11:52 UTC, dbnorth commented on src/components/student/performances/StudentPerformances.vue
> +    console.log(response.data);
Removed

2023-08-09 11:53 UTC, dbnorth commented on src/components/student/performances/PerformanceDialogBody.vue
> +          >{{ critique.userRole.user.firstName }}
fixed

2023-08-09 12:20 UTC, dbnorth commented on src/components/student/performances/StudentPerformanceCard.vue
> +                    View Critique
fixed

2023-08-09 12:41 UTC, dbnorth commented on src/components/student/performances/StudentPerformanceCard.vue
> +<script setup>
fixed the padding.  The Critique button looks find when it is full page.  Looking for an answer.

2023-08-09 18:27 UTC, dbnorth commented on src/components/student/performances/StudentPerformanceCard.vue
> +<script setup>
done

2023-08-09 22:33 UTC, dbnorth commented on src/components/student/performances/PerformanceDialogBody.vue
> +                  >Accuracy - Grade: {{ critique.accuracyGrade }}
I think we can leave it the way it is for now.

2023-08-11 21:21 UTC, AndrewClubb commented on src/components/student/performances/StudentPerformances.vue
> +  console.log(performances.value);
This doesn't look like it has been removed

2023-08-13 21:57 UTC, dbnorth commented on src/components/student/performances/StudentPerformances.vue
> +  console.log(performances.value);
done

2023-08-13 22:04 UTC, AndrewClubb approved these changes

2023-08-13 22:04 UTC, merged