Faculty create critique ac
OC-ComputerScience/performancescheduling-frontend pull request #51
Opened 2023-09-05 20:01 UTC by dbnorth

2023-09-11 00:39 UTC, JuliaFlores21 requested changes
I think we should keep consistency and add a cancel button when faculty is adding a critique.

2023-09-14 14:47 UTC, JuliaFlores21 approved these changes
good

2023-09-14 14:47 UTC, dbnorth commented on src/components/faculty/critique/FacultyCreateCritiqueDialog.vue
> +                Clear
fixed

2023-09-14 14:47 UTC, dbnorth commented on src/views/BaseView.vue
> +          v-if="this.$route.path === '/facultyCreateCritique'"
fixed

2023-09-14 14:50 UTC, merged