Initial update
OC-ComputerScience/performancescheduling-frontend pull request #54
Opened 2023-09-06 20:00 UTC by dbnorth

2023-09-07 23:24 UTC, JuliaFlores21 commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +console.log(isAdmin);
this console.log should me removed

2023-09-07 23:25 UTC, JuliaFlores21 commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +console.log(loginStore.currentRole.roleId);
this console.log should me removed

2023-09-07 23:25 UTC, JuliaFlores21 commented on src/components/admin/maintain/pieces/MaintainPieces.vue
> +console.log(isAdmin);
this console.log should me removed

2023-09-07 23:25 UTC, JuliaFlores21 commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +console.log("isAdmin:" + props.isAdmin);
this console.log should me removed

2023-09-07 23:25 UTC, JuliaFlores21 commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +console.log("isEdmin:" + props.isEdit);
this console.log should me removed

2023-09-07 23:26 UTC, JuliaFlores21 requested changes
Everything works fine. We just need to remove the console.logs

2023-09-08 19:53 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +console.log(isAdmin);
done

2023-09-08 19:54 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieces.vue
> +console.log(isAdmin);
done

2023-09-08 19:55 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +console.log("isEdmin:" + props.isEdit);
done

2023-09-08 19:56 UTC, JuliaFlores21 approved these changes
looks good

2023-09-08 19:58 UTC, dbnorth commented on src/components/admin/maintain/pieces/MaintainPieceCard.vue
> +console.log(loginStore.currentRole.roleId);
done

2023-09-08 19:58 UTC, dbnorth commented on src/components/admin/maintain/pieces/PieceDialogBody.vue
> +console.log("isAdmin:" + props.isAdmin);
done

2023-09-08 19:58 UTC, merged